version: 2

project_name: orchestra-mcp

builds:
  - main: ./src/cmd/
    binary: orchestra-mcp
    ldflags:
      - -s -w
      - -X github.com/orchestra-mcp/mcp/src/version.Version={{.Version}}
      - -X github.com/orchestra-mcp/mcp/src/version.Commit={{.Commit}}
      - -X github.com/orchestra-mcp/mcp/src/version.Date={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^ci:"]

nfpms:
  - package_name: orchestra-mcp
    maintainer: Orchestra MCP <hello@orchestra-mcp.dev>
    homepage: https://github.com/orchestra-mcp/mcp
    description: AI-powered project management via Model Context Protocol
    formats: [deb, rpm]
