name: Feature Request
description: Suggest a new feature or tool for the MCP plugin
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like to see.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New MCP tool
        - Enhance existing tool
        - Workflow improvement
        - TOON format change
        - Integration (Jira, Linear, GitHub, etc.)
        - CLI / Init improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: When managing projects with AI, I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? For new tools, describe the tool name, inputs, and expected output.
      placeholder: |
        Tool: `assign_task`
        Input: { "task_id": "TASK-1", "assignee": "alice" }
        Output: Updated task with assignee field set
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: willing
    attributes:
      label: Would you submit a PR?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
